### PR TITLE
Upgrade to JUnit 4

### PR DESCRIPTION
**Pull request by edysli**
JUnit version 5 has been out for a while so it's time to upgrade from version 3 to 4, right? ;)

My end goal with this is to remove `AbstractFlowExecutionTests`'s inheritance on JUnit 3's `TestCase` which causes all sorts of weirdness in my tests using Spring Webflow with JUnit 4 (need to use `@RunWith(JUnit4.class)`). This prevents my flow tests from using JUnit 5.

### CODE REVIEW

**Comment by edysli** [comment]
I've already signed Pivotal's CLA, by the way.

**Comment by edysli** [comment]
Also filed as [SWF-1738 on jira.spring.io](https://jira.spring.io/projects/SWF/issues/SWF-1738).

**Comment by rstoyanchev** [comment]
@edysli, thanks for the contribution! 

I think internal tests should go directly to JUnit 5 while the flow test support should make it optional to upgrade to either JUnit 5 or 4. That way we could get this into a maintenance release without waiting for another minor or major release.

I've also split this into two parts, [SWF-1739](https://jira.spring.io/browse/SWF-1739) and [SWF-1740](https://jira.spring.io/browse/SWF-1740) with some initial thoughts. If you'd like to rework the PR accordingly that would be much appreciated!

**Comment by edysli** [comment]
Hey @rstoyanchev, thanks for sharing your thoughts! :) That makes sense, I'll split this PR in two then.

**Pull request closed without merging**
