### PR TITLE
Migrate spring-faces to Jakarta EE

### PR DESCRIPTION
**Pull request by liptga**
- FlowResourceResolver.java is removed, since was deprecated - see https://github.com/jakartaee/faces/issues/1583
- diverse libraries are updated

### CODE REVIEW

**Review by rstoyanchev — APPROVED** [review]
Thanks for the changes and apologies for the delay. Overall looks good and tests pass. Have you tried it with a sample or application yet? I'm wondering if the changes to all the constants work as expected.

**Comment by liptga** [comment]
> Have you tried it with a sample or application yet?

@rstoyanchev We have migrated our framework on Spring Boot 3 and Jakarta EE 10, and we used also Spring-faces. All of our unit tests are passing with this changeset, and our demo UI app also works as expected. However it could be surely tested deeper by others. Maybe a release candidate could be built and published, and then lets see if it also works for others.

**Comment by keith-h** [comment]
When is 3.0.0 due to be released?

**Comment by rstoyanchev** [comment]
It is released now.

**Comment by martin654** [comment]
@rstoyanchev Hi, we are migrating our app to Spring Boot 3.1 and Jakarta EE10 these days, what a challanging task. But, SpringWebflow version 3.0.0 looks really good! I haven't found any issue so far. Many thanks for this major upgrade!

**Pull request closed without merging**
